# merge rule used by Mergify
# strict is enabled
pull_request_rules: 
  - name: automatic merge when CI(pre-merge passes and 1+ approved reviews
    conditions: 
      - "#approved-reviews-by>=1"
      - status-success=pre-merge
      - base=master 
    actions: 
      merge: 
        method: merge
        strict: true