# won't trigger on branch/PR/merge 
trigger: none

pr: none

stages:
- stage: Bazel_Build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: 'VMSSPool'

    steps: 

    - script: |
        bazel version
      displayName: 'Show Bazel Version'

    - script: |
        bazel clean --expunge
      displayName: 'Bazel Clean'

    - script: |
        bazel test --remote_cache=http://remotecache.eastus.cloudapp.azure.com:9090 --test_tag_filters=-benchmark ...
      displayName: 'Run All Non-benchmark Tests'       
