# Independent (periodic) pipeline taking Artifact and Producing Container
# pushed to ACR

# won't trigger for branch push/PR merge
trigger: none 

# won't trigger for PR created
pr: none

schedules:
- cron: "0 7 * * *"
  displayName: Daily 7am Build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPackage@1
  inputs:
    packageType: 'upack'
    feed: 'minerva-poc-github/binaries'
    definition: 'abseil'
    version: '*'
    files: '**'
    extract: false
    downloadPath: '$(System.ArtifactsDirectory)' 

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: minervapocRegistryServiceConnection1

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: minervapocRegistryServiceConnection1
    repository: 'abseil'
    command: 'buildAndPush'
    Dockerfile: 'containers/independent/Dockerfile'
    buildContext: '$(System.ArtifactsDirectory)'
    tags: 'latest'
